### ISSUE TITLE
Master MIS> Committee> View > Uploaded photo not visible

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#103]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/d9f3370b-f1ef-46da-ad28-db46172ef5d4)

**Comment by neetishvayuz** [comment]
Images deleted from folder. It is working.

**Comment by neetishvayuz** [comment]
10 minutes

**Comment by neetishvayuz** [comment]
Please try with latest data upload and its working fine as expected

**Comment by Anupriyabanger** [comment]
Same with new data also
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/26fc7c03-f07e-4e7c-b0c8-2411ab068d6f)
