### ISSUE TITLE
Master MIS> Committee> View> showing default image

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#104]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/7d29fa92-4d1c-49ec-924e-d6d886389617)

**Comment by neetishvayuz** [comment]
There is no issue found.
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/125471304/0e8b3d73-e228-442a-91ea-8a3ef899757b)

**Comment by neetishvayuz** [comment]
10 minutes
