### ISSUE TITLE
Master MIS> View> On reaching view option, sidebar stops highlighting the module

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#105]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/51689815-5a90-47b2-8b14-564f7fdb98d2)

**Comment by neetishvayuz** [comment]
1:30 hours

**Comment by Anupriyabanger** [comment]
@neetishvayuz No change
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/02f84968-29bc-47b9-b3bf-e221c177dc81)
