### ISSUE TITLE
Data Module> Canal scheduling> Add> not able to add new data

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#106]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/4c07f21f-d6de-4598-9e6a-448e86c73ffc)

**Comment by Anupriyabanger** [comment]
@neetishvayuz Issue not resolved. Still not able to add new data.
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/844aee24-bf3d-4492-a0d8-48d80ea356e4)

**Comment by neetishvayuz** [comment]
20 min
