### ISSUE TITLE
Data module> canal scheduling> Add> Make canal an Input box

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#108]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/62939555-fd67-49f6-96b8-d1c9cd285bee)

**Comment by neetishvayuz** [comment]
Similar to design.

**Comment by Anupriyabanger** [comment]
@neetishvayuz Need to change the design for better UX.
