### ISSUE TITLE
Master MIS> Employee> Add> On clicking Preview button, preview screen not opening

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#120]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/f138be31-185b-4cf6-baba-2486b5e0a02b)

**Comment by abdulkhira1** [comment]
changed preview to submit

**Comment by Anupriyabanger** [comment]
@abdul not able to submit/add the data.
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/ea1c8cac-e333-4914-a12b-394af781f16e)

**Comment by rohitrvayuz** [comment]
Not working
