### ISSUE TITLE
Get employee list api not working

### ISSUE THREAD

**Issue by abdulkhira1** [Anupriyabanger/MapMyIndia#137]
https://13.232.69.92/api/api/Employee/GetEmployees

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-d5d68b938481c3ba833cf8a4d3114410-1a879b231d2ee968-00"
}

**Comment by neetishvayuz** [comment]
Issue Resolved.

I have added Pagination here thats why you got this issue, Please pass IsPagination=true and it will resolve your issue.
