### ISSUE TITLE
User permission list api error

### ISSUE THREAD

**Issue by abdulkhira1** [Anupriyabanger/MapMyIndia#138]
https://13.232.69.92/api/api/User/GetPermissionByUserId

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
    "title": "Unsupported Media Type",
    "status": 415,
    "traceId": "00-f484f965e751167955528b0f7181e184-f3b6c4e9ac2d2b64-00"
}

**Comment by neetishvayuz** [comment]
Resolved please try now with passing the params

![image](https://github.com/Anupriyabanger/MapMyIndia/assets/125471304/10044bdf-8803-4443-84e7-d6befb351b9a)
