### ISSUE TITLE
Common/UploadFile api not working

### ISSUE THREAD

**Issue by abdulkhira1** [Anupriyabanger/MapMyIndia#162]
https://13.232.69.92/api/api/Common/UploadFile

{
    "responseCode": 400,
    "responseMsg": "Could not find a part of the path 'C:\\SharedFiles\\Document\\Common\\511c5e62-d85b-4142-bc41-6470b7b921ee.png'.",
    "data": null,
    "errors": []
}

**Comment by neetishvayuz** [comment]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/125471304/6b40b32a-e646-4721-9e55-ce3f99a9061a)
