### ISSUE TITLE
App> To show notification don't show android, show proper format

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#165]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/c7e5db4b-232e-4895-a770-91e3a29c5713)

**Comment by abdulkhira1** [comment]
@Anupriyabanger need MMI app logo

**Comment by abdulkhira1** [comment]
@naveesha-vayuz @Anupriyabanger need MMI app icon
