### ISSUE TITLE
App> Application is signing out on clicking back

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#166]

**Comment by rohitrvayuz** [comment]
Not fixed

**Comment by abdulkhira1** [comment]
@rohitrvayuz @Anupriyabanger at development phase i commented some code 
so it'll work when we finish testing

**Comment by Anupriyabanger** [comment]
Not resolved 

https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/3570205b-1f5d-47c8-8545-33ccbf7b5e0f
