### ISSUE TITLE
select user screen > scroll is not happening in loop

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/MapMyIndia#21]
As in if the user has reached the end it should be able to slide back to farmer after it slides left in one go, same goes with farmer but in slide right.

**Comment by rohitrvayuz** [comment]
Not done

**Comment by abdulkhira1** [comment]
@rohitrvayuz @naveesha-vayuz @Anupriyabanger scroll in loop not possible in current ui
