### ISSUE TITLE
App> All modules> Change Active/Inactive colours

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#214]

**Comment by abdulkhira1** [comment]
@Anupriyabanger in which module
pls attach screenshot

**Comment by Anupriyabanger** [comment]
@abdulkhira1 Please change employee module
Current UI: ![Uploading Screenshot_20230719-113612_Map My India.jpg…]()
Figma UI: 
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/7469eb93-de83-4803-8b20-bab66eb005cb)
