### ISSUE TITLE
App> All modules> Filter not working

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#218]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/5489dad8-c09b-4abd-bbcd-f50e589d883f)

**Comment by abdulkhira1** [comment]
@neetishvayuz in list api status filter not working

**Comment by abdulkhira1** [comment]
https://mmi.vayuz.com/api/api/Cad/GetOffices?Status=false

**Comment by rohitrvayuz** [comment]
Not fixed for all modules

**Comment by rohitrvayuz** [comment]
What is the update here? @abdulkhira1 @neetishvayuz
