### ISSUE TITLE
login using otp in farmer but farmer api returns permission denied

### ISSUE THREAD

**Issue by abdulkhira1** [Anupriyabanger/MapMyIndia#231]
https://mmi.vayuz.com/api/api/Farmer/GetCanal

**Comment by rohitrvayuz** [comment]
@neetishvayuz @abdulkhira1 What is the status here?

**Comment by rohitrvayuz** [comment]
What is the update here? @abdulkhira1 @neetishvayuz

**Comment by neetishvayuz** [comment]
Its done and deployed on staging/production
