### ISSUE TITLE
App> Farmer and Contractor> Redirection Issue

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#243]
On clicking the back button from OTP screen, show a prompt that "Sure, you want to exit the sign-in process?"- Confirm and Cancel.

https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/e8eaacb5-b63c-471a-ac16-7801667a3b74

**Comment by rohitrvayuz** [comment]
@abdulkhira1 Why are we having same issues again and again?

**Comment by abdulkhira1** [comment]
@rohitrvayuz this was not a issue

**Comment by rohitrvayuz** [comment]
> @rohitrvayuz this was not a issue

This was pointed out during Employee module too. And this should be handled while development. This is carelessness at your end. Please make sure this is not repeated.
