### ISSUE TITLE
App> Farmer> Canal Scheduling> Data not updating real time 

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#245]
I added new canals in the Admin, but the same is not reflected in the app in real time.

**Comment by rohitrvayuz** [comment]
@Anupriyabanger I think you will need to refresh to view the added data unless we are using sockets.

**Comment by neetishvayuz** [comment]
i tried debugging but found that its working fine.

it will good if you can share a screen recording for this issue or we can a do a Quick call for this

**Comment by rohitrvayuz** [comment]
> i tried debugging but found that its working fine.
> 
> it will good if you can share a screen recording for this issue or we can a do a Quick call for this

Ok. We will discuss in the evening call today
