### ISSUE TITLE
App> Contractor> Search Issues> Showing wrong issues 

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#257]
Issues bottom sheet showing details of the Project details.
![Screenshot_20230724-155708_Map](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/eddf6928-d9f9-4f54-b01a-669acb4a9e21)

**Comment by abdulkhira1** [comment]
@Anupriyabanger there is 3 option to search
select project
contractor
type of issue
