### ISSUE TITLE
App> Employee> No indication on filter applied/ removed

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#262]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/c82781fa-2942-4abe-97d7-f6baea67aa29)

**Comment by abdulkhira1** [comment]
@naveesha-vayuz need filled filter icon

**Comment by rohitrvayuz** [comment]
> @naveesha-vayuz need filled filter icon

Nothing is required here. Just make the filter icon color as grey if not applied
