### ISSUE TITLE
App> User permission> Detail screen not working

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#276]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/89aa4bc5-1f6f-4e48-93e3-7da1de3f1c05)

**Comment by Anupriyabanger** [comment]
User permission and Job allocation details screen still not opening



https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/d7002ac9-a178-4487-9227-c4fd37c09ec0

**Comment by abdulkhira1** [comment]
@Anupriyabanger there is no details screen in figma
