### ISSUE TITLE
App> Employee> Redirection Issue

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#277]
On clicking the CAD module and then moving to any other module, clicking the back button from a mobile takes me to the CAD module again.  

https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/ca40d2f6-82c0-42d8-b447-fe6aa72e2bd6

**Comment by rohitrvayuz** [comment]
Closing this as invalid
