### ISSUE TITLE
Farmer> Issue> Calendar is not opening 

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/MapMyIndia#28]
![Screenshot_2023-04-20-18-12-19-23_ee3606ef8b6644cfd5df025d6da59dc9](https://user-images.githubusercontent.com/121479721/233369794-fcd12116-3009-41c4-a6ae-4defbe2fac43.jpg)

Calendar is not opening on click of date field

**Comment by abdulkhira1** [comment]
@Anupriyabanger removed calendor
