### ISSUE TITLE
App> Employee> Wrong redirection

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/MapMyIndia#286]
I was on Contractor module but on clicking back button from mobile it is taking me to previous screen with changing the module name on the hamburger menu.

https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/110fb528-b5b2-4cbb-94b8-272d97183983

**Comment by abdulkhira1** [comment]
@Anupriyabanger on backpress opened drawer instead of previous screen

**Comment by rajasrivastava101** [comment]
Still not resolved , on going back , drawer is getting opened rather previous screen.

**Comment by abdulkhira1** [comment]
@rajasrivastava101 pls discuss with @Anupriyabanger and check my comment

**Comment by abdulkhira1** [comment]
@Anupriyabanger pls check
