### ISSUE TITLE
label should be visible once selected

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Anupriyabanger/MapMyIndia#311]
<img width="422" alt="image" src="https://github.com/Anupriyabanger/MapMyIndia/assets/18699624/b6bc2bf8-b186-4c1f-aa2a-ba91724f3111">

**Comment by Anupriyabanger** [comment]
Not resolved
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/15052eec-02fa-4940-b5e0-1f2708802626)

**Comment by abdulkhira1** [comment]
@Anupriyabanger pls share video recording
