### ISSUE TITLE
Data not being deleted from CAD Circle

### ISSUE THREAD

**Issue by rohitrvayuz** [Anupriyabanger/MapMyIndia#314]
Please check this

https://github.com/Anupriyabanger/MapMyIndia/assets/78350161/5ba1a00a-4c3c-49d8-aef4-8263179d1053

**Comment by abdulkhira1** [comment]
{"responseCode":200,"responseMsg":"Error caught: Can not be delete: Possible reason will be there may be foreign key relationship","data":null,"errors":[]}


@neetishvayuz

**Comment by abdulkhira1** [comment]
https://mmi.vayuz.com/api/api/Cad/DeleteCircle

{"ids":["21"]}

**Comment by neetishvayuz** [comment]
It can not be deleted please check the error message it is connected with some parent child data so foreign key relationship will not be able to delete the parent data.
