### ISSUE TITLE
App > Home screen > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/MapMyIndia#339]
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/129847373/8f941eed-2262-4574-a69c-cefc21ec8fef)
the map is not visible fully on the home screen.

**Comment by Anupriyabanger** [comment]
Can't check, shows unauthorised access
![Screenshot_20230919-231645_Command](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/49d04d3b-eb7a-4232-9ffc-72b8ec4bcbfa)

**Comment by abdulkhira1** [comment]
#294 duplicate
