### ISSUE TITLE
CAD > Employee > CAD Office > Action menu items not coming as bottomsheet and coming with different card bg colour 

### ISSUE THREAD

**Issue by VayuzBidyut** [Anupriyabanger/MapMyIndia#360]
![1000001434](https://github.com/Anupriyabanger/MapMyIndia/assets/78781245/13b016fb-e88a-4b6c-b56b-b2e93aaa2904)

**Comment by rohitrvayuz** [comment]
These are not supposed to be a bottom sheet according to Figma
