### ISSUE TITLE
Farmer > Canal Scheduling list screen> Hamburger > Check description

### ISSUE THREAD

**Issue by naveesha-vayuz** [Anupriyabanger/MapMyIndia#7]
![WhatsApp Image 2023-04-19 at 19 00 14](https://user-images.githubusercontent.com/121479721/233090394-8b56335d-ed50-4cfc-a1db-bba7a722e881.jpg)

Hamburger 
    - alignment and size of the logo is wrong, align it the left and decrease the size of the logo a lil
    - alignment of the cross button and the icon used is wrong
    - no background effect on selected menu option
    - the spacing in between the option is too little 
    - Setting Option is missing
    
Please refer figma for assistance

**Comment by Anupriyabanger** [comment]
Issue not resolved.
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/c529ee55-8cea-4c55-a1ae-7a79cc4a56dd)
