### ISSUE TITLE
Home screen > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [Anupriyabanger/MapMyIndia#9]
after clicking on print , there should be a pop up of print the page.

**Comment by neetishvayuz** [comment]
Large amount of data available in future that's why i downloaded the page so that format can't be changed

**Comment by Anupriyabanger** [comment]
@neetishvayuz Direct print command should apply.
![image](https://github.com/Anupriyabanger/MapMyIndia/assets/109590553/a2bf1296-7f60-4681-a627-c88d95615594)
